const countries = [
{ name:"Afghanistan", tld:[".af"], code:"+93" },
{ name:"Albania", tld:[".al"], code:"+355" },
{ name:"Algeria", tld:[".dz"], code:"+213" },
{ name:"Andorra", tld:[".ad"], code:"+376" },
{ name:"Angola", tld:[".ao"], code:"+244" },
{ name:"Antigua and Barbuda", tld:[".ag"], code:"+1" },
{ name:"Argentina", tld:[".ar"], code:"+54" },
{ name:"Armenia", tld:[".am"], code:"+374" },
{ name:"Australia", tld:[".au"], code:"+61" },
{ name:"Austria", tld:[".at"], code:"+43" },
{ name:"Azerbaijan", tld:[".az"], code:"+994" },

{ name:"Bahamas", tld:[".bs"], code:"+1" },
{ name:"Bahrain", tld:[".bh"], code:"+973" },
{ name:"Bangladesh", tld:[".bd"], code:"+880" },
{ name:"Barbados", tld:[".bb"], code:"+1" },
{ name:"Belarus", tld:[".by"], code:"+375" },
{ name:"Belgium", tld:[".be"], code:"+32" },
{ name:"Belize", tld:[".bz"], code:"+501" },
{ name:"Benin", tld:[".bj"], code:"+229" },
{ name:"Bhutan", tld:[".bt"], code:"+975" },
{ name:"Bolivia", tld:[".bo"], code:"+591" },
{ name:"Bosnia and Herzegovina", tld:[".ba"], code:"+387" },
{ name:"Botswana", tld:[".bw"], code:"+267" },
{ name:"Brazil", tld:[".br"], code:"+55" },
{ name:"Brunei", tld:[".bn"], code:"+673" },
{ name:"Bulgaria", tld:[".bg"], code:"+359" },
{ name:"Burkina Faso", tld:[".bf"], code:"+226" },
{ name:"Burundi", tld:[".bi"], code:"+257" },

{ name:"Cabo Verde", tld:[".cv"], code:"+238" },
{ name:"Cambodia", tld:[".kh"], code:"+855" },
{ name:"Cameroon", tld:[".cm"], code:"+237" },
{ name:"Canada", tld:[".ca"], code:"+1" },
{ name:"Central African Republic", tld:[".cf"], code:"+236" },
{ name:"Chad", tld:[".td"], code:"+235" },
{ name:"Chile", tld:[".cl"], code:"+56" },
{ name:"China", tld:[".cn"], code:"+86" },
{ name:"Colombia", tld:[".co"], code:"+57" },
{ name:"Comoros", tld:[".km"], code:"+269" },
{ name:"Congo (Congo-Brazzaville)", tld:[".cg"], code:"+242" },
{ name:"Costa Rica", tld:[".cr"], code:"+506" },
{ name:"Croatia", tld:[".hr"], code:"+385" },
{ name:"Cuba", tld:[".cu"], code:"+53" },
{ name:"Cyprus", tld:[".cy"], code:"+357" },
{ name:"Czech Republic", tld:[".cz"], code:"+420" },

{ name:"Denmark", tld:[".dk"], code:"+45" },
{ name:"Djibouti", tld:[".dj"], code:"+253" },
{ name:"Dominica", tld:[".dm"], code:"+1" },
{ name:"Dominican Republic", tld:[".do"], code:"+1" },

{ name:"Ecuador", tld:[".ec"], code:"+593" },
{ name:"Egypt", tld:[".eg"], code:"+20" },
{ name:"El Salvador", tld:[".sv"], code:"+503" },
{ name:"Equatorial Guinea", tld:[".gq"], code:"+240" },
{ name:"Eritrea", tld:[".er"], code:"+291" },
{ name:"Estonia", tld:[".ee"], code:"+372" },
{ name:"Eswatini", tld:[".sz"], code:"+268" },
{ name:"Ethiopia", tld:[".et"], code:"+251" },

{ name:"Fiji", tld:[".fj"], code:"+679" },
{ name:"Finland", tld:[".fi"], code:"+358" },
{ name:"France", tld:[".fr"], code:"+33" },

{ name:"Gabon", tld:[".ga"], code:"+241" },
{ name:"Gambia", tld:[".gm"], code:"+220" },
{ name:"Georgia", tld:[".ge"], code:"+995" },
{ name:"Germany", tld:[".de"], code:"+49" },
{ name:"Ghana", tld:[".gh"], code:"+233" },
{ name:"Greece", tld:[".gr"], code:"+30" },
{ name:"Grenada", tld:[".gd"], code:"+1" },
{ name:"Guatemala", tld:[".gt"], code:"+502" },
{ name:"Guinea", tld:[".gn"], code:"+224" },
{ name:"Guinea-Bissau", tld:[".gw"], code:"+245" },
{ name:"Guyana", tld:[".gy"], code:"+592" },

{ name:"Haiti", tld:[".ht"], code:"+509" },
{ name:"Honduras", tld:[".hn"], code:"+504" },
{ name:"Hungary", tld:[".hu"], code:"+36" },

{ name:"Iceland", tld:[".is"], code:"+354" },
{ name:"India", tld:[".in"], code:"+91" },
{ name:"Indonesia", tld:[".id"], code:"+62" },
{ name:"Iran", tld:[".ir"], code:"+98" },
{ name:"Iraq", tld:[".iq"], code:"+964" },
{ name:"Ireland", tld:[".ie"], code:"+353" },
{ name:"Israel", tld:[".il"], code:"+972" },
{ name:"Italy", tld:[".it"], code:"+39" },

{ name:"Jamaica", tld:[".jm"], code:"+1" },
{ name:"Japan", tld:[".jp"], code:"+81" },
{ name:"Jordan", tld:[".jo"], code:"+962" },

{ name:"Kazakhstan", tld:[".kz"], code:"+7" },
{ name:"Kenya", tld:[".ke"], code:"+254" },
{ name:"Kiribati", tld:[".ki"], code:"+686" },
{ name:"Kuwait", tld:[".kw"], code:"+965" },
{ name:"Kyrgyzstan", tld:[".kg"], code:"+996" },

{ name:"Laos", tld:[".la"], code:"+856" },
{ name:"Latvia", tld:[".lv"], code:"+371" },
{ name:"Lebanon", tld:[".lb"], code:"+961" },
{ name:"Lesotho", tld:[".ls"], code:"+266" },
{ name:"Liberia", tld:[".lr"], code:"+231" },
{ name:"Libya", tld:[".ly"], code:"+218" },
{ name:"Liechtenstein", tld:[".li"], code:"+423" },
{ name:"Lithuania", tld:[".lt"], code:"+370" },
{ name:"Luxembourg", tld:[".lu"], code:"+352" },

{ name:"Madagascar", tld:[".mg"], code:"+261" },
{ name:"Malawi", tld:[".mw"], code:"+265" },
{ name:"Malaysia", tld:[".my"], code:"+60" },
{ name:"Maldives", tld:[".mv"], code:"+960" },
{ name:"Mali", tld:[".ml"], code:"+223" },
{ name:"Malta", tld:[".mt"], code:"+356" },
{ name:"Marshall Islands", tld:[".mh"], code:"+692" },
{ name:"Mauritania", tld:[".mr"], code:"+222" },
{ name:"Mauritius", tld:[".mu"], code:"+230" },
{ name:"Mexico", tld:[".mx"], code:"+52" },
{ name:"Micronesia", tld:[".fm"], code:"+691" },
{ name:"Moldova", tld:[".md"], code:"+373" },
{ name:"Monaco", tld:[".mc"], code:"+377" },
{ name:"Mongolia", tld:[".mn"], code:"+976" },
{ name:"Montenegro", tld:[".me"], code:"+382" },
{ name:"Morocco", tld:[".ma"], code:"+212" },
{ name:"Mozambique", tld:[".mz"], code:"+258" },
{ name:"Myanmar", tld:[".mm"], code:"+95" },

{ name:"Namibia", tld:[".na"], code:"+264" },
{ name:"Nauru", tld:[".nr"], code:"+674" },
{ name:"Nepal", tld:[".np"], code:"+977" },
{ name:"Netherlands", tld:[".nl"], code:"+31" },
{ name:"New Zealand", tld:[".nz"], code:"+64" },
{ name:"Nicaragua", tld:[".ni"], code:"+505" },
{ name:"Niger", tld:[".ne"], code:"+227" },
{ name:"Nigeria", tld:[".ng"], code:"+234" },
{ name:"North Macedonia", tld:[".mk"], code:"+389" },
{ name:"Norway", tld:[".no"], code:"+47" },

{ name:"Oman", tld:[".om"], code:"+968" },

{ name:"Pakistan", tld:[".pk"], code:"+92" },
{ name:"Palau", tld:[".pw"], code:"+680" },
{ name:"Panama", tld:[".pa"], code:"+507" },
{ name:"Papua New Guinea", tld:[".pg"], code:"+675" },
{ name:"Paraguay", tld:[".py"], code:"+595" },
{ name:"Peru", tld:[".pe"], code:"+51" },
{ name:"Philippines", tld:[".ph"], code:"+63" },
{ name:"Poland", tld:[".pl"], code:"+48" },
{ name:"Portugal", tld:[".pt"], code:"+351" },

{ name:"Qatar", tld:[".qa"], code:"+974" },

{ name:"Romania", tld:[".ro"], code:"+40" },
{ name:"Russia", tld:[".ru"], code:"+7" },
{ name:"Rwanda", tld:[".rw"], code:"+250" },

{ name:"Saint Kitts and Nevis", tld:[".kn"], code:"+1" },
{ name:"Saint Lucia", tld:[".lc"], code:"+1" },
{ name:"Saint Vincent and the Grenadines", tld:[".vc"], code:"+1" },
{ name:"Samoa", tld:[".ws"], code:"+685" },
{ name:"San Marino", tld:[".sm"], code:"+378" },
{ name:"Sao Tome and Principe", tld:[".st"], code:"+239" },
{ name:"Saudi Arabia", tld:[".sa"], code:"+966" },
{ name:"Senegal", tld:[".sn"], code:"+221" },
{ name:"Serbia", tld:[".rs"], code:"+381" },
{ name:"Seychelles", tld:[".sc"], code:"+248" },
{ name:"Sierra Leone", tld:[".sl"], code:"+232" },
{ name:"Singapore", tld:[".sg"], code:"+65" },
{ name:"Slovakia", tld:[".sk"], code:"+421" },
{ name:"Slovenia", tld:[".si"], code:"+386" },
{ name:"Solomon Islands", tld:[".sb"], code:"+677" },
{ name:"Somalia", tld:[".so"], code:"+252" },
{ name:"South Africa", tld:[".za"], code:"+27" },
{ name:"South Korea", tld:[".kr"], code:"+82" },
{ name:"South Sudan", tld:[".ss"], code:"+211" },
{ name:"Spain", tld:[".es"], code:"+34" },
{ name:"Sri Lanka", tld:[".lk"], code:"+94" },
{ name:"Sudan", tld:[".sd"], code:"+249" },
{ name:"Suriname", tld:[".sr"], code:"+597" },
{ name:"Sweden", tld:[".se"], code:"+46" },
{ name:"Switzerland", tld:[".ch"], code:"+41" },
{ name:"Syria", tld:[".sy"], code:"+963" },

{ name:"Taiwan", tld:[".tw"], code:"+886" },
{ name:"Tajikistan", tld:[".tj"], code:"+992" },
{ name:"Tanzania", tld:[".tz"], code:"+255" },
{ name:"Thailand", tld:[".th"], code:"+66" },
{ name:"Timor-Leste", tld:[".tl"], code:"+670" },
{ name:"Togo", tld:[".tg"], code:"+228" },
{ name:"Tonga", tld:[".to"], code:"+676" },
{ name:"Trinidad and Tobago", tld:[".tt"], code:"+1" },
{ name:"Tunisia", tld:[".tn"], code:"+216" },
{ name:"Turkey", tld:[".tr"], code:"+90" },
{ name:"Turkmenistan", tld:[".tm"], code:"+993" },

{ name:"Uganda", tld:[".ug"], code:"+256" },
{ name:"Ukraine", tld:[".ua"], code:"+380" },
{ name:"United Arab Emirates", tld:[".ae"], code:"+971" },
{ name:"United Kingdom", tld:[".uk"], code:"+44" },
{ name: "Guernsey", tld: [".gg"], code: "+44" },
{ name:"United States", tld:[".us"], code:"+1" },
{ name:"Uruguay", tld:[".uy"], code:"+598" },
{ name:"Uzbekistan", tld:[".uz"], code:"+998" },

{ name:"Vanuatu", tld:[".vu"], code:"+678" },
{ name:"Vatican City", tld:[".va"], code:"+379" },
{ name:"Venezuela", tld:[".ve"], code:"+58" },
{ name:"Vietnam", tld:[".vn"], code:"+84" },

{ name:"Yemen", tld:[".ye"], code:"+967" },

{ name:"Zambia", tld:[".zm"], code:"+260" },
{ name:"Zimbabwe", tld:[".zw"], code:"+263" }

];

countries.push({
  name: "Global",
  tld: [
    ".com", ".org", ".net",
    ".io", ".ai",
    ".dev", ".app",
    ".tech", ".xyz",
    ".site", ".online",
    ".store", ".shop",
    ".blog", ".info",
    ".cloud", ".digital",
    ".solutions", ".agency",
    ".studio", ".design",
    ".space", ".live",
    ".today", ".world"
  ],
  code: ""
});